tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "ncdu"
brew "zsh"
brew "nvm"
brew "zsh-completions"
cask "visual-studio-code"
cask "google-chrome"
cask "discord"
cask "iterm2"
cask "notion"
brew "git-cola"
brew "git-flow"