### TAP
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"

### BREW
brew "ncdu"
brew "nvm"
brew "neovim"
brew "stow"
brew "liquibase"
brew "terminal-notifier"
brew "watchman"
brew "zsh"
brew "zsh-completions"

### CASK
cask "git-credential-manager"
cask "google-chrome"
cask "discord"
cask "spotify"
cask "iterm2"
cask "vscodium"
cask "intellij-idea"
cask "beekeeper-studio"
cask "docker"
cask "the-unarchiver"