code --install-extension antfu.icons-carbon
code --install-extension danielsousadev.styled-components-snippets
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.copilot
code --install-extension igorming.useful-react-snippets
code --install-extension jiza.theme-panda-high-contrast
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension shd101wyy.markdown-preview-enhanced