source-file ~/.dotfiles/tmux/settings.conf
source-file ~/.dotfiles/tmux/plugins.conf
source-file ~/.dotfiles/tmux/bindings.conf
source-file ~/.dotfiles/tmux/vim.conf
source-file ~/.dotfiles/tmux/copy.conf
source-file ~/.dotfiles/tmux/theme.conf
run '~/.dotfiles/tmux/plugins/tpm/tpm'
run '~/.dotfiles/tmux/plugins/tmux-cpu/cpu.tmux'
set -g status-left-length 500
set -g status-right-length 2000
