bind-key -r G run-shell "~/.dotfiles/scripts/tmux/setup_new_tmux.sh" \; display "loaded sessions"
bind-key S command-prompt -p "Session name:,Path (leave empty for $HOME):" "run-shell '~/.dotfiles/scripts/tmux/create_dev_session.sh %1 %2'"
bind-key -r E run-shell "~/.dotfiles/scripts/tmux/create_tmux_dev_env.sh" \; display "Dev env created"
bind-key r source-file ~/.tmux.conf \; display "Config reloaded!"

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind L last-window

bind C-f new-window -n "session-switcher" "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
