############################################################
# GENERAL KEYBINDS
############################################################

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Custom scripts
bind -r G run-shell "~/.dotfiles/scripts/tmux/setup_new_tmux.sh" \; display "Sessions loaded"
bind -r E run-shell "~/.dotfiles/scripts/tmux/create_tmux_dev_env.sh" \; display "Dev env created"

# Splits
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# Resize
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Popup LazyGit (power move)
bind g display-popup -E -w 90% -h 90% "lazygit"
