############################################################
# SESSION MANAGEMENT
############################################################

# FZF session switcher
bind C-f display-popup -E -w 70% -h 70% \
  "tmux list-sessions | sed -E 's/:.*$//' \
  | grep -v \"^$(tmux display-message -p '#S')\$\" \
  | fzf --reverse \
  | xargs tmux switch-client -t"

# Quick new session popup
bind s command-prompt -p "New session name:" "new-session -s '%%'"
