set-option -g status-style bg=default
set status-bg default
set -g status-right "#[fg=brightblack,bg=default,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] #(gitmux \"#{pane_current_path}\") #[fg=white,bg=brightblack,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack]  #{ram_percentage} #[fg=cyan,bg=brightblack,nobold,noitalics,nounderscore]#[fg=black,bg=cyan,bold]  #{cpu_percentage} "
