set -g @config_dir "$HOME/.dotfiles/tmux"

source-file "$HOME/.dotfiles/tmux/core.conf"
source-file "$HOME/.dotfiles/tmux/plugins.conf"
source-file "$HOME/.dotfiles/tmux/navigation.conf"
source-file "$HOME/.dotfiles/tmux/copy-mode.conf"
source-file "$HOME/.dotfiles/tmux/keybindings.conf"
source-file "$HOME/.dotfiles/tmux/sessions.conf"
source-file "$HOME/.dotfiles/tmux/theme.conf"
